import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    const val com_adarshr_test_logger_gradle_plugin: String =
            "com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin:" +
            Versions.com_adarshr_test_logger_gradle_plugin

    const val com_diffplug_gradle_spotless_gradle_plugin: String =
            "com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:" +
            Versions.com_diffplug_gradle_spotless_gradle_plugin

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" +
            Versions.com_gradle_build_scan_gradle_plugin

    const val com_gradle_plugin_publish_gradle_plugin: String =
            "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin:" +
            Versions.com_gradle_plugin_publish_gradle_plugin

    /**
     * https://github.com/square/kotlinpoet */
    const val kotlinpoet: String = "com.squareup:kotlinpoet:" + Versions.kotlinpoet

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val detekt_cli: String = "io.gitlab.arturbosch.detekt:detekt-cli:" +
            Versions.io_gitlab_arturbosch_detekt

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:" +
            Versions.io_gitlab_arturbosch_detekt

    const val org_gradle_kotlin_kotlin_dsl_gradle_plugin: String =
            "org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:" +
            Versions.org_gradle_kotlin_kotlin_dsl_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-compiler-embeddable:" + Versions.kotlin_compiler_embeddable

    /**
     * https://kotlinlang.org/ */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.kotlin_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.kotlin_reflect

    /**
     * https://kotlinlang.org/ */
    const val kotlin_sam_with_receiver: String = "org.jetbrains.kotlin:kotlin-sam-with-receiver:" +
            Versions.kotlin_sam_with_receiver

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.kotlin_scripting_compiler_embeddable

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.kotlin_stdlib_jdk8

    /**
     * https://kotlinlang.org/ */
    const val kotlin_test_junit5: String = "org.jetbrains.kotlin:kotlin-test-junit5:" +
            Versions.kotlin_test_junit5

    /**
     * https://github.com/junit-pioneer/junit-pioneer */
    const val junit_pioneer: String = "org.junit-pioneer:junit-pioneer:" + Versions.junit_pioneer

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://github.com/mockito/mockito */
    const val mockito_junit_jupiter: String = "org.mockito:mockito-junit-jupiter:" +
            Versions.mockito_junit_jupiter

    const val pl_allegro_tech_build_axion_release_gradle_plugin: String =
            "pl.allegro.tech.build.axion-release:pl.allegro.tech.build.axion-release.gradle.plugin:" +
            Versions.pl_allegro_tech_build_axion_release_gradle_plugin
}
