language: java
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
env:
  - GRADLE_CURRENT_VERSION=5.1.1
  - GRADLE_CURRENT_VERSION=5.0
  - GRADLE_CURRENT_VERSION=4.10.3
  - GRADLE_CURRENT_VERSION=4.9